# .github/workflows/release.yml
name: Release app
on:
  workflow_dispatch:
jobs:
  build:
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     os:
    #       [
    #         { name: 'linux', image: 'ubuntu-latest' },
    #         { name: 'windows', image: 'windows-latest' },
    #         { name: 'macos', image: 'macos-latest' },
    #       ]
    # runs-on: ${{ matrix.os.image }}
    runs-on: macos-latest
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Remove package-lock.json
        uses: JesseTG/rm@v1.0.3
        with:
          path: ./package-lock.json
      - name: Install Dependencies
        run: npm i
      - name: 'Create env file'
        run: |
          touch .env
          echo IDENTITY="${{ secrets.IDENTITY }}" >> .env
          echo APPLE_ID="${{ secrets.APPLE_ID }}" >> .env
          echo APPLE_TEAM_ID="${{ secrets.APPLE_TEAM_ID }}" >> .env
          echo APPLE_PASSWORD="${{ secrets.APPLE_PASSWORD }}" >> .env
      - name: Build application
        run: make all
      # - name: Publish application
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: make publish
