
# .github/workflows/build-windows.yml
name: Build Linux Releases
on:
  workflow_dispatch:
jobs:
  build-linux-x64:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: get-package-version
        id: package-version
        uses: beaconbrigade/package-json-version@v0.3.2
      - name: Install Dependencies
        run: npm i
      - name: Build script
        run: make linux-x64
      - name: List files
        id: filelist
        uses: the-coding-turtle/ga-file-list@v0.1
        with:
          directory: "out/make/zip/linux/x64"
      - name: Print files
        run: echo "${{ steps.filelist.outputs.files }}"
      # - name: Publish Release
      #   run: gh release upload v${{ steps.package-version.outputs.version}} "out/make/zip/linux/x64/Witsy-${{ steps.package-version.outputs.version}}-linux-x64.zip"
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
