# .github/workflows/release.yml
name: Build Windows x64
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: get-package-version
        id: package-version
        uses: beaconbrigade/package-json-version@v0.3.2
      - name: Install Dependencies
        run: npm i
      - name: Build script
        run: ./build.ps1
      - name: Publish Release
        run: gh release upload -R nbonamy/electron-squirrel-test v${{ steps.package-version.outputs.version}} "out/make/squirrel.windows/x64/Witsy-${{ steps.package-version.outputs.version}}-x64 Setup.exe" "out/make/squirrel.windows/x64/witsy-${{ steps.package-version.outputs.version}}-x64-full.nupkg"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
